// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserData.Data;

#nullable disable

namespace UserData.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240330150829_TestUser")]
    partial class TestUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("UserData.Models.User", b =>
                {
                    b.Property<string>("PersonalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonalId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            PersonalId = "197001152345",
                            Email = "johan.nilsson@test.com",
                            Name = "Johan Nilsson",
                            PhoneNumber = "07234567890"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
